version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    labels: [security, dependencies]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    labels: [security, dependencies]
